var data=[
    {
      "menuName":"全部作品",
      "className":"all-icon"
    },
    {
      "menuName":"全部分类",
      "className":"arw-icon",
      "nextMenu":[
           {
              "menuName":"全部分类",
              "nextMenu":[
                  {
                      "menuName":"成人用品"
                  },
                  {
                      "menuName":"母婴用品",
                  },
                  {
                      "menuName":"生活服务",
                  },
                  {
                      "menuName":"护肤彩妆",
                  },                               
                  {
                      "menuName":"运动户外",
                  },
                  {
                      "menuName":"汇吃美食",
                  },
                  {
                      "menuName":"花鸟文娱",
                  },                               
                  {
                      "menuName":"珠宝配饰",
                  },
                  {
                      "menuName":"汇吃美食",
                  },
                  {
                      "menuName":"花鸟文娱",
                  }
                 ]
           },
           {
              "menuName":"店铺首页",
              "nextMenu":[
                  {
                      "menuName":"成人用品"
                  },
                  {
                      "menuName":"母婴用品",
                  },
                  {
                      "menuName":"生活服务",
                  },
                  {
                      "menuName":"护肤彩妆",
                  },                               
                  {
                      "menuName":"运动户外",
                  },
                  {
                      "menuName":"汇吃美食",
                  },
                  {
                      "menuName":"花鸟文娱",
                  },                               
                  {
                      "menuName":"珠宝配饰",
                  },
                  {
                      "menuName":"汇吃美食",
                  },
                  {
                      "menuName":"花鸟文娱",
                  },                               
                  {
                      "menuName":"珠宝配饰",
                  },
                  {
                      "menuName":"汇吃美食",
                  },
                  {
                      "menuName":"花鸟文娱",
                  }
                 ]
           },
           {
              "menuName":"原创教程",
              "nextMenu":[
                  {
                      "menuName":"成人用品"
                  },
                  {
                      "menuName":"母婴用品",
                  },
                  {
                      "menuName":"生活服务",
                  },
                  {
                      "menuName":"护肤彩妆",
                  },                               
                  {
                      "menuName":"运动户外",
                  },
                  {
                      "menuName":"汇吃美食",
                  }
                 ]
           },
           {
              "menuName":"UI设计",
              "nextMenu":[
                  {
                      "menuName":"成人用品"
                  },
                  {
                      "menuName":"母婴用品",
                  },
                  {
                      "menuName":"生活服务",
                  }
                 ]
           },
           {
              "menuName":"专题页"
           },
           {
              "menuName":"详情页"
           },
           {
              "menuName":"直通车"
           },
           {
              "menuName":"店铺首页"
           },
           {
              "menuName":"个人简历"
           },
           {
              "menuName":"Banner/钻展"
           }
      ]
    },
    {
      "menuName":"首页推荐",
      "className":"rem-icon"
    },
    {
      "menuName":"编辑精选",
      "className":"det-icon"
    },
    {
      "menuName":"最新作品",
      "className":"arw-icon",
      "nextMenu":
      [
          {
             "menuName":"点赞最多"
          },
          {
             "menuName":"评论最多"
          },
          {
             "menuName":"浏览最多"
          }
      ]
    },
    {
      "menuName":"邓明宇",
      "className":"arw-icon",
      "nextMenu":
      [
          {
             "menuName":"原创"
          },
          {
             "menuName":"转载"
          }
      ]
    }
  ]